language: ruby
cache: bundler # caching bundler gem packages will speed up build

branches:
  only:
  - master

script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination docs

deploy:
  provider: pages
  local-dir: ./docs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true

############### Git Submodule (for resume) Hack ###############

# Handle git submodules yourself, based off of https://github.com/algolia/examples/issues/24
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive