language: ruby
cache:
  bundler: true
  # Looks like I can't cache node_modules since _resume is a git submodule :'(
  # In the future, I could look into temporarily moving the folder out, then back after init
  # directories:
  #  - _resume/node_modules

sudo: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

branches:
  only:
    - master

script:
  - pushd _resume && node ./index.js && popd
  - JEKYLL_ENV=production bundle exec jekyll build --destination docs

deploy:
  provider: pages
  local-dir: ./docs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true

############### Git Submodule (for resume) Hack ###############

# Handle git submodules yourself, based off of https://github.com/algolia/examples/issues/24
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - pushd _resume && npm install && popd
