title: Andrew McOlash
subtitle: Software Engineer
email: amcolash@gmail.com

main_header: "Developer, Maker, Hacker"
description: > # this means to ignore newlines until next variable
  The personal website of Andrew McOlash, developer and creator
  of cool things!

resume: "/resume"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amcolash.com" # the base hostname & protocol for your site

github_username: "amcolash"
# twitter_username: "amcolash"
linkedin_name: "Andrew McOlash"
linkedin_username: "andrew-mcolash"

# Build settings
markdown: kramdown
theme: minima
destination: docs

exclude:
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - jekyll-cache/
  - README.md
  - feed.xml
  - scripts/
  - .travis.yml

# Plugins
plugins:
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

plugins_dir: ./_plugins
page_gen:
  - data: 'projects'
    template: 'project'
    name: 'name'
    dir: 'projects'
