# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Andrew McOlash
subtitle: Software Engineer
email: amcolash@gmail.com

main_header: "Developer, Maker, Hacker"
description: > # this means to ignore newlines until next variable
  The personal website of Andrew McOlash, developer and creator
  of cool things!

resume: "/resume"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amcolash.com" # the base hostname & protocol for your site

github_username: "amcolash"
# twitter_username: "amcolash"
linkedin_name: "Andrew McOlash"
linkedin_username: "andrew-mcolash"

# Build settings
markdown: kramdown
theme: minima
destination: docs

exclude:
  - 'README.md'
  - 'Gemfile*'
  - 'feed.xml'
  - 'scripts/'
  - '.vscode'
  - '.travis.yml'
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-sitemap

plugins_dir: ./_plugins
page_gen:
  - data: 'projects'
    template: 'project'
    name: 'name'
    dir: 'projects'
