application: amcolash
version: 1
runtime: python27
api_version: 1
threadsafe: yes

#default_expiration: "30d"

handlers:

- url: /(.*\.(gif|png|jpg|ico|js|css|pdf))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|pdf))

- url: /
  static_files: index.html
  upload: index.html